# Deploy
name: Deploy to Azure Container App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  #AZURE_CONTAINER_NAME: "container-deployement-api"
  CONTAINER_APP_NAME: "prod-ap-container-deployment-api"
  RESOURCE_GROUP: "prod-rg-wolds-hr"
  AZURE_CONTAINER_REGISTRY: "prodcrglobal"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v4	
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x		
    - name: Build
      run: dotnet build ./container-deployment-api/container-deployment-api.csproj --configuration Release 
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to ACR
      uses: docker/login-action@v3
      with:
        registry: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}	
    - name: Build and push container image to ACR
      uses: docker/build-push-action@v6
      with:
        context: container-deployment-api
        push: true
        tags: ${{ env.AZURE_CONTAINER_REGISTRY}}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
        file: container-deployment-api/Dockerfile 
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }} 
    - name: Deploy and Azure Container Apps
      uses: azure/container-apps-deploy-action@v1	  
      with:
        imageToDeploy: ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_APP_NAME }}:${{ github.sha }}
        resourceGroup: ${{ env.RESOURCE_GROUP }}
        containerAppName: ${{ env.CONTAINER_APP_NAME }}
        environmentVariables: |
          ASPNETCORE_ENVIRONMENT=Development
